/* This file was generated by SableCC (http://www.sablecc.org/). */

package tiny.analysis;

import tiny.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAPlusExp(APlusExp node);
    void caseAMinusExp(AMinusExp node);
    void caseAFactorExp(AFactorExp node);
    void caseAMultFactor(AMultFactor node);
    void caseADivdFactor(ADivdFactor node);
    void caseATermFactor(ATermFactor node);
    void caseAParenTerm(AParenTerm node);
    void caseAIdTerm(AIdTerm node);
    void caseANumberTerm(ANumberTerm node);

    void caseTEol(TEol node);
    void caseTBlank(TBlank node);
    void caseTStar(TStar node);
    void caseTSlash(TSlash node);
    void caseTPlus(TPlus node);
    void caseTMinus(TMinus node);
    void caseTLPar(TLPar node);
    void caseTRPar(TRPar node);
    void caseTNumber(TNumber node);
    void caseTId(TId node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
