/* This file was generated by SableCC (http://www.sablecc.org/). */

package tiny.node;

import tiny.analysis.*;

@SuppressWarnings("nls")
public final class TEol extends Token
{
    public TEol(String text)
    {
        setText(text);
    }

    public TEol(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEol(getText(), getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEol(this);
    }
}
